#!/usr/bin/env python3
# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0
"""Regenerates qtctokens.{h,cpp} from Utils' Theme::Color and
StyleHelper::UiElement enums.

The properties have to be real properties with a notify signal, because a QML
binding over a Q_INVOKABLE never re-evaluates and the theme can change while
Qt Creator runs. Run this after adding a token; the design system autotest
fails if the output is stale.
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UTILS = os.path.normpath(os.path.join(HERE, '..', 'utils'))

LICENSE = """// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

// Generated by generate-tokens.py. Do not edit.
"""


def camel(parts):
    out = parts[0].lower()
    for p in parts[1:]:
        out += p[0].upper() + p[1:]
    return out


def color_tokens():
    text = open(os.path.join(UTILS, 'theme', 'theme.h'), encoding='utf-8').read()
    keys = re.findall(r'^\s*(Token_[A-Za-z0-9_]+),', text, re.M)
    return [(camel(k[len('Token_'):].split('_')), k) for k in keys]


def ui_elements():
    text = open(os.path.join(UTILS, 'stylehelper.h'), encoding='utf-8').read()
    block = text[text.index('enum UiElement {'):]
    block = block[:block.index('};')]
    keys = re.findall(r'^\s*(UiElement[A-Za-z0-9]+),', block, re.M)
    out = []
    for k in keys:
        name = k[len('UiElement'):]
        out.append((name[0].lower() + name[1:], k))
    return out


def main():
    colors = color_tokens()
    fonts = ui_elements()

    header = [LICENSE, '', '#pragma once', '', '#include "qtcquick_global.h"', '',
              '#include <QColor>', '#include <QFont>', '#include <QObject>',
              '#include <QQmlEngine>', '', 'namespace QtcQuick {', '']

    header += ['// Qt Creator\'s Figma colour tokens.',
               'class QTCQUICK_EXPORT Tokens : public QObject', '{', '    Q_OBJECT',
               '    QML_ELEMENT', '    QML_SINGLETON', '']
    for prop, _ in colors:
        header.append('    Q_PROPERTY(QColor %s READ %s NOTIFY changed)' % (prop, prop))
    header += ['', 'public:', '    explicit Tokens(QObject *parent = nullptr);', '']
    for prop, _ in colors:
        header.append('    QColor %s() const;' % prop)
    header += ['', 'signals:', '    void changed();', '};', '']

    header += ['// Qt Creator\'s UI font roles, with their line heights.',
               'class QTCQUICK_EXPORT Fonts : public QObject', '{', '    Q_OBJECT',
               '    QML_ELEMENT', '    QML_SINGLETON', '']
    for prop, _ in fonts:
        header.append('    Q_PROPERTY(QFont %s READ %s NOTIFY changed)' % (prop, prop))
        header.append('    Q_PROPERTY(int %sLineHeight READ %sLineHeight NOTIFY changed)'
                      % (prop, prop))
    header += ['', 'public:', '    explicit Fonts(QObject *parent = nullptr);', '']
    for prop, _ in fonts:
        header.append('    QFont %s() const;' % prop)
        header.append('    int %sLineHeight() const;' % prop)
    header += ['', 'signals:', '    void changed();', '};', '',
               '} // namespace QtcQuick', '']

    source = [LICENSE, '', '#include "qtctokens.h"', '',
              '#include <utils/stylehelper.h>', '#include <utils/theme/theme.h>', '',
              'namespace QtcQuick {', '',
              'Tokens::Tokens(QObject *parent)', '    : QObject(parent)', '{',
              '    connect(Utils::ThemeWatcher::instance(), &Utils::ThemeWatcher::themeChanged,',
              '            this, &Tokens::changed);', '}', '']
    for prop, key in colors:
        source += ['QColor Tokens::%s() const' % prop, '{',
                   '    return Utils::creatorColor(Utils::Theme::%s);' % key, '}', '']
    source += ['Fonts::Fonts(QObject *parent)', '    : QObject(parent)', '{',
               '    connect(Utils::ThemeWatcher::instance(), &Utils::ThemeWatcher::themeChanged,',
               '            this, &Fonts::changed);', '}', '']
    for prop, key in fonts:
        source += ['QFont Fonts::%s() const' % prop, '{',
                   '    return Utils::StyleHelper::uiFont(Utils::StyleHelper::%s);' % key,
                   '}', '',
                   'int Fonts::%sLineHeight() const' % prop, '{',
                   '    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::%s);' % key,
                   '}', '']
    source += ['} // namespace QtcQuick', '']

    open(os.path.join(HERE, 'qtctokens.h'), 'w', encoding='utf-8').write('\n'.join(header))
    open(os.path.join(HERE, 'qtctokens.cpp'), 'w', encoding='utf-8').write('\n'.join(source))
    print('%d colour tokens, %d font roles' % (len(colors), len(fonts)))


if __name__ == '__main__':
    sys.exit(main())
