// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

// Generated by generate-tokens.py. Do not edit.


#pragma once

#include "qtcquick_global.h"

#include <QColor>
#include <QFont>
#include <QObject>
#include <QQmlEngine>

namespace QtcQuick {

// Qt Creator's Figma colour tokens.
class QTCQUICK_EXPORT Tokens : public QObject
{
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

    Q_PROPERTY(QColor basicBlack READ basicBlack NOTIFY changed)
    Q_PROPERTY(QColor basicWhite READ basicWhite NOTIFY changed)
    Q_PROPERTY(QColor accentDefault READ accentDefault NOTIFY changed)
    Q_PROPERTY(QColor accentMuted READ accentMuted NOTIFY changed)
    Q_PROPERTY(QColor accentSubtle READ accentSubtle NOTIFY changed)
    Q_PROPERTY(QColor backgroundDefault READ backgroundDefault NOTIFY changed)
    Q_PROPERTY(QColor backgroundMuted READ backgroundMuted NOTIFY changed)
    Q_PROPERTY(QColor backgroundSubtle READ backgroundSubtle NOTIFY changed)
    Q_PROPERTY(QColor foregroundDefault READ foregroundDefault NOTIFY changed)
    Q_PROPERTY(QColor foregroundMuted READ foregroundMuted NOTIFY changed)
    Q_PROPERTY(QColor foregroundSubtle READ foregroundSubtle NOTIFY changed)
    Q_PROPERTY(QColor textDefault READ textDefault NOTIFY changed)
    Q_PROPERTY(QColor textMuted READ textMuted NOTIFY changed)
    Q_PROPERTY(QColor textSubtle READ textSubtle NOTIFY changed)
    Q_PROPERTY(QColor textAccent READ textAccent NOTIFY changed)
    Q_PROPERTY(QColor textOnAccent READ textOnAccent NOTIFY changed)
    Q_PROPERTY(QColor strokeStrong READ strokeStrong NOTIFY changed)
    Q_PROPERTY(QColor strokeMuted READ strokeMuted NOTIFY changed)
    Q_PROPERTY(QColor strokeSubtle READ strokeSubtle NOTIFY changed)
    Q_PROPERTY(QColor notificationAlertDefault READ notificationAlertDefault NOTIFY changed)
    Q_PROPERTY(QColor notificationAlertMuted READ notificationAlertMuted NOTIFY changed)
    Q_PROPERTY(QColor notificationAlertSubtle READ notificationAlertSubtle NOTIFY changed)
    Q_PROPERTY(QColor notificationSuccessDefault READ notificationSuccessDefault NOTIFY changed)
    Q_PROPERTY(QColor notificationSuccessMuted READ notificationSuccessMuted NOTIFY changed)
    Q_PROPERTY(QColor notificationSuccessSubtle READ notificationSuccessSubtle NOTIFY changed)
    Q_PROPERTY(QColor notificationNeutralDefault READ notificationNeutralDefault NOTIFY changed)
    Q_PROPERTY(QColor notificationNeutralMuted READ notificationNeutralMuted NOTIFY changed)
    Q_PROPERTY(QColor notificationNeutralSubtle READ notificationNeutralSubtle NOTIFY changed)
    Q_PROPERTY(QColor notificationDangerDefault READ notificationDangerDefault NOTIFY changed)
    Q_PROPERTY(QColor notificationDangerMuted READ notificationDangerMuted NOTIFY changed)
    Q_PROPERTY(QColor notificationDangerSubtle READ notificationDangerSubtle NOTIFY changed)
    Q_PROPERTY(QColor gradient01Start READ gradient01Start NOTIFY changed)
    Q_PROPERTY(QColor gradient01End READ gradient01End NOTIFY changed)
    Q_PROPERTY(QColor gradient02Start READ gradient02Start NOTIFY changed)
    Q_PROPERTY(QColor gradient02End READ gradient02End NOTIFY changed)

public:
    explicit Tokens(QObject *parent = nullptr);

    QColor basicBlack() const;
    QColor basicWhite() const;
    QColor accentDefault() const;
    QColor accentMuted() const;
    QColor accentSubtle() const;
    QColor backgroundDefault() const;
    QColor backgroundMuted() const;
    QColor backgroundSubtle() const;
    QColor foregroundDefault() const;
    QColor foregroundMuted() const;
    QColor foregroundSubtle() const;
    QColor textDefault() const;
    QColor textMuted() const;
    QColor textSubtle() const;
    QColor textAccent() const;
    QColor textOnAccent() const;
    QColor strokeStrong() const;
    QColor strokeMuted() const;
    QColor strokeSubtle() const;
    QColor notificationAlertDefault() const;
    QColor notificationAlertMuted() const;
    QColor notificationAlertSubtle() const;
    QColor notificationSuccessDefault() const;
    QColor notificationSuccessMuted() const;
    QColor notificationSuccessSubtle() const;
    QColor notificationNeutralDefault() const;
    QColor notificationNeutralMuted() const;
    QColor notificationNeutralSubtle() const;
    QColor notificationDangerDefault() const;
    QColor notificationDangerMuted() const;
    QColor notificationDangerSubtle() const;
    QColor gradient01Start() const;
    QColor gradient01End() const;
    QColor gradient02Start() const;
    QColor gradient02End() const;

signals:
    void changed();
};

// Qt Creator's UI font roles, with their line heights.
class QTCQUICK_EXPORT Fonts : public QObject
{
    Q_OBJECT
    QML_ELEMENT
    QML_SINGLETON

    Q_PROPERTY(QFont h1 READ h1 NOTIFY changed)
    Q_PROPERTY(int h1LineHeight READ h1LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h2 READ h2 NOTIFY changed)
    Q_PROPERTY(int h2LineHeight READ h2LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h3 READ h3 NOTIFY changed)
    Q_PROPERTY(int h3LineHeight READ h3LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h4 READ h4 NOTIFY changed)
    Q_PROPERTY(int h4LineHeight READ h4LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h5 READ h5 NOTIFY changed)
    Q_PROPERTY(int h5LineHeight READ h5LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h6 READ h6 NOTIFY changed)
    Q_PROPERTY(int h6LineHeight READ h6LineHeight NOTIFY changed)
    Q_PROPERTY(QFont h6Capital READ h6Capital NOTIFY changed)
    Q_PROPERTY(int h6CapitalLineHeight READ h6CapitalLineHeight NOTIFY changed)
    Q_PROPERTY(QFont body1 READ body1 NOTIFY changed)
    Q_PROPERTY(int body1LineHeight READ body1LineHeight NOTIFY changed)
    Q_PROPERTY(QFont body2 READ body2 NOTIFY changed)
    Q_PROPERTY(int body2LineHeight READ body2LineHeight NOTIFY changed)
    Q_PROPERTY(QFont buttonMedium READ buttonMedium NOTIFY changed)
    Q_PROPERTY(int buttonMediumLineHeight READ buttonMediumLineHeight NOTIFY changed)
    Q_PROPERTY(QFont buttonSmall READ buttonSmall NOTIFY changed)
    Q_PROPERTY(int buttonSmallLineHeight READ buttonSmallLineHeight NOTIFY changed)
    Q_PROPERTY(QFont labelMedium READ labelMedium NOTIFY changed)
    Q_PROPERTY(int labelMediumLineHeight READ labelMediumLineHeight NOTIFY changed)
    Q_PROPERTY(QFont labelSmall READ labelSmall NOTIFY changed)
    Q_PROPERTY(int labelSmallLineHeight READ labelSmallLineHeight NOTIFY changed)
    Q_PROPERTY(QFont captionStrong READ captionStrong NOTIFY changed)
    Q_PROPERTY(int captionStrongLineHeight READ captionStrongLineHeight NOTIFY changed)
    Q_PROPERTY(QFont caption READ caption NOTIFY changed)
    Q_PROPERTY(int captionLineHeight READ captionLineHeight NOTIFY changed)
    Q_PROPERTY(QFont iconStandard READ iconStandard NOTIFY changed)
    Q_PROPERTY(int iconStandardLineHeight READ iconStandardLineHeight NOTIFY changed)
    Q_PROPERTY(QFont iconActive READ iconActive NOTIFY changed)
    Q_PROPERTY(int iconActiveLineHeight READ iconActiveLineHeight NOTIFY changed)

public:
    explicit Fonts(QObject *parent = nullptr);

    QFont h1() const;
    int h1LineHeight() const;
    QFont h2() const;
    int h2LineHeight() const;
    QFont h3() const;
    int h3LineHeight() const;
    QFont h4() const;
    int h4LineHeight() const;
    QFont h5() const;
    int h5LineHeight() const;
    QFont h6() const;
    int h6LineHeight() const;
    QFont h6Capital() const;
    int h6CapitalLineHeight() const;
    QFont body1() const;
    int body1LineHeight() const;
    QFont body2() const;
    int body2LineHeight() const;
    QFont buttonMedium() const;
    int buttonMediumLineHeight() const;
    QFont buttonSmall() const;
    int buttonSmallLineHeight() const;
    QFont labelMedium() const;
    int labelMediumLineHeight() const;
    QFont labelSmall() const;
    int labelSmallLineHeight() const;
    QFont captionStrong() const;
    int captionStrongLineHeight() const;
    QFont caption() const;
    int captionLineHeight() const;
    QFont iconStandard() const;
    int iconStandardLineHeight() const;
    QFont iconActive() const;
    int iconActiveLineHeight() const;

signals:
    void changed();
};

} // namespace QtcQuick
