// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

// Generated by generate-tokens.py. Do not edit.


#include "qtctokens.h"

#include <utils/stylehelper.h>
#include <utils/theme/theme.h>

namespace QtcQuick {

Tokens::Tokens(QObject *parent)
    : QObject(parent)
{
    connect(Utils::ThemeWatcher::instance(), &Utils::ThemeWatcher::themeChanged,
            this, &Tokens::changed);
}

QColor Tokens::basicBlack() const
{
    return Utils::creatorColor(Utils::Theme::Token_Basic_Black);
}

QColor Tokens::basicWhite() const
{
    return Utils::creatorColor(Utils::Theme::Token_Basic_White);
}

QColor Tokens::accentDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Accent_Default);
}

QColor Tokens::accentMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Accent_Muted);
}

QColor Tokens::accentSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Accent_Subtle);
}

QColor Tokens::backgroundDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Background_Default);
}

QColor Tokens::backgroundMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Background_Muted);
}

QColor Tokens::backgroundSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Background_Subtle);
}

QColor Tokens::foregroundDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Foreground_Default);
}

QColor Tokens::foregroundMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Foreground_Muted);
}

QColor Tokens::foregroundSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Foreground_Subtle);
}

QColor Tokens::textDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Text_Default);
}

QColor Tokens::textMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Text_Muted);
}

QColor Tokens::textSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Text_Subtle);
}

QColor Tokens::textAccent() const
{
    return Utils::creatorColor(Utils::Theme::Token_Text_Accent);
}

QColor Tokens::textOnAccent() const
{
    return Utils::creatorColor(Utils::Theme::Token_Text_On_Accent);
}

QColor Tokens::strokeStrong() const
{
    return Utils::creatorColor(Utils::Theme::Token_Stroke_Strong);
}

QColor Tokens::strokeMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Stroke_Muted);
}

QColor Tokens::strokeSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Stroke_Subtle);
}

QColor Tokens::notificationAlertDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Alert_Default);
}

QColor Tokens::notificationAlertMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Alert_Muted);
}

QColor Tokens::notificationAlertSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Alert_Subtle);
}

QColor Tokens::notificationSuccessDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Success_Default);
}

QColor Tokens::notificationSuccessMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Success_Muted);
}

QColor Tokens::notificationSuccessSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Success_Subtle);
}

QColor Tokens::notificationNeutralDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Neutral_Default);
}

QColor Tokens::notificationNeutralMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Neutral_Muted);
}

QColor Tokens::notificationNeutralSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Neutral_Subtle);
}

QColor Tokens::notificationDangerDefault() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Danger_Default);
}

QColor Tokens::notificationDangerMuted() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Danger_Muted);
}

QColor Tokens::notificationDangerSubtle() const
{
    return Utils::creatorColor(Utils::Theme::Token_Notification_Danger_Subtle);
}

QColor Tokens::gradient01Start() const
{
    return Utils::creatorColor(Utils::Theme::Token_Gradient01_Start);
}

QColor Tokens::gradient01End() const
{
    return Utils::creatorColor(Utils::Theme::Token_Gradient01_End);
}

QColor Tokens::gradient02Start() const
{
    return Utils::creatorColor(Utils::Theme::Token_Gradient02_Start);
}

QColor Tokens::gradient02End() const
{
    return Utils::creatorColor(Utils::Theme::Token_Gradient02_End);
}

Fonts::Fonts(QObject *parent)
    : QObject(parent)
{
    connect(Utils::ThemeWatcher::instance(), &Utils::ThemeWatcher::themeChanged,
            this, &Fonts::changed);
}

QFont Fonts::h1() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH1);
}

int Fonts::h1LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH1);
}

QFont Fonts::h2() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH2);
}

int Fonts::h2LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH2);
}

QFont Fonts::h3() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH3);
}

int Fonts::h3LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH3);
}

QFont Fonts::h4() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH4);
}

int Fonts::h4LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH4);
}

QFont Fonts::h5() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH5);
}

int Fonts::h5LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH5);
}

QFont Fonts::h6() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH6);
}

int Fonts::h6LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH6);
}

QFont Fonts::h6Capital() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementH6Capital);
}

int Fonts::h6CapitalLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementH6Capital);
}

QFont Fonts::body1() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementBody1);
}

int Fonts::body1LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementBody1);
}

QFont Fonts::body2() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementBody2);
}

int Fonts::body2LineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementBody2);
}

QFont Fonts::buttonMedium() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementButtonMedium);
}

int Fonts::buttonMediumLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementButtonMedium);
}

QFont Fonts::buttonSmall() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementButtonSmall);
}

int Fonts::buttonSmallLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementButtonSmall);
}

QFont Fonts::labelMedium() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementLabelMedium);
}

int Fonts::labelMediumLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementLabelMedium);
}

QFont Fonts::labelSmall() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementLabelSmall);
}

int Fonts::labelSmallLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementLabelSmall);
}

QFont Fonts::captionStrong() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementCaptionStrong);
}

int Fonts::captionStrongLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementCaptionStrong);
}

QFont Fonts::caption() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementCaption);
}

int Fonts::captionLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementCaption);
}

QFont Fonts::iconStandard() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementIconStandard);
}

int Fonts::iconStandardLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementIconStandard);
}

QFont Fonts::iconActive() const
{
    return Utils::StyleHelper::uiFont(Utils::StyleHelper::UiElementIconActive);
}

int Fonts::iconActiveLineHeight() const
{
    return Utils::StyleHelper::uiFontLineHeight(Utils::StyleHelper::UiElementIconActive);
}

} // namespace QtcQuick
